name: MainFlow

on:
    push:
        branches:
            - main

jobs:
    build-test-deploy:
        env:
          USERN1: ${{vars.DOCKER_USERNAME}}

        runs-on: ubuntu-22.04
        steps:
          - name: Checkout
            uses: actions/checkout@v5.0.0
          - name: build docker
            run: |
              docker compose build --no-cache
          - name: tests
            run: |
              docker compose run --rm -d --remove-orphans --no-deps --name bk_con backend
              docker compose exec backend ./manage.py test
          - name: lint python code
            run: |
             docker compose exec backend ruff check --fix
             docker compose exec backend ruff format -v
             docker stop bk_con
          - name: push to docker 
            run: |
              echo docker login -u '$USERN1'
              echo docker login -u $USERN1
              echo docker login -u ${{vars.DOCKER_USERNAME}}
              echo docker login -u '${{vars.DOCKER_USERNAME}}'
              echo docker login -u "${{vars.DOCKER_USERNAME}}"

