name: MainFlow

on:
    push:
        branches:
            - main

jobs:
    build-test-deploy:
        env:
          REMOTE_USERNAME: ${{secrets.DDK_USERNAME}}
          REMOTE_PASS: ${{secrets.DDK_PASSWORD}}
          
        runs-on: ubuntu-22.04
        steps:
          - name: Checkout
            uses: actions/checkout@v5.0.0
          - name: build docker
            run: |
              docker build --no-cache -t $REMOTE_USERNAME/ere1223:v0.0.1
          - name: tests
            run: |
              docker compose run --rm -d --remove-orphans --no-deps --name bk_con backend
              docker compose exec backend ./manage.py test
          - name: lint python code
            run: |
             docker compose exec backend ruff check --fix
             docker compose exec backend ruff format -v
             docker stop bk_con
          - name: push to docker 
            run: |
              docker login -u$REMOTE_USERNAME -p$REMOTE_PASS
              docker push $REMOTE_USERNAME/ere1223:v0.0.1
