name: MainFlow

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
          - name: Checkout
            uses: actions/checkout@v5.0.0
          - name: build docker
            run: |
              docker compose build --no-cache
          # - name: init docker
          #   uses: docker/metadata-action@v5
          # - name: Set up python
          #   id: setup-python
          #   uses: actions/setup-python@v5
          #   with:
          #     python-version: '3.13'
