name: MainFlow

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
          - name: Checkout
            uses: actions/checkout@v5.0.0
          - name: build docker
            run: |
              docker compose build --no-cache
          - name: tests
            run: |
              docker compose run --rm -d --remove-orphans --no-deps --name bk_con backend
              docker compose exec backend ./manage.py test
              docker stop bk_con
