name: MainFlow

on:
    push:
        branches:
            - main

jobs:
    build-job:
        runs-on: ubuntu-22.04
        steps:
            - run: echo 'Hello world'
            - name: Checkout to code
              uses: actions/checkout@v5.0.0
            - name: lint workflow yml
              uses: devops-actions/actionlint@v0.1.2
            - name: List Files
              run: |
                echo "The Repo ${{github.repository}} has following files:"
                tree
    test:
        runs-on: ubuntu-22.04
        steps:
          - name: Checkout
            uses: actions/checkout@v5.0.0
          - name: Set up python
            id: setup-python
            uses: actions/setup-python@v5
            with:
              python-version: '3.13'
          - name: Install Poetry
            uses: snok/install-poetry@v1
          - name: install
            run: poetry install  
          - name: lint the code
            run: poetry run ruff check --fix 
          - name: run tests
            run: poetry run ./manage.py test 